# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Realm', :git => "https://github.com/realm/realm-cocoa.git", :branch => "tg/object-level-permissions-tests", :submodules => true
  pod 'RealmSwift', :git => "https://github.com/realm/realm-cocoa.git", :branch => "tg/object-level-permissions-tests", :submodules => true

  # Pods for ToDo

end
