# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '~> 3.1.0'
  # Pods for ToDo

end
