# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'RealmSwift'

# Build the specific branch w/PartialSync
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :branch => 'mar/partial-sync', :submodules => true
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :branch => 'mar/partial-sync', :submodules => true

 # In case using the branch name fails, use the specific commit hash...
  #pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :commit => '6c6a337c032d2519e9affeb69359d58f82f68432'
  #pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :commit => '6c6a337c032d2519e9affeb69359d58f82f68432'

  # Pods for ToDo

end
